/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'master-customer': RouteRecordInfo<'master-customer', '/master/customer', Record<never, never>, Record<never, never>>,
    'master-organization-setting-company': RouteRecordInfo<'master-organization-setting-company', '/master/organization-setting/company', Record<never, never>, Record<never, never>>,
    'master-organization-setting-organization-data': RouteRecordInfo<'master-organization-setting-organization-data', '/master/organization-setting/organization-data', Record<never, never>, Record<never, never>>,
    'master-organization-setting-organization-data-add-edit-organization-dialog': RouteRecordInfo<'master-organization-setting-organization-data-add-edit-organization-dialog', '/master/organization-setting/organization-data/AddEditOrganizationDialog', Record<never, never>, Record<never, never>>,
    'master-product': RouteRecordInfo<'master-product', '/master/product', Record<never, never>, Record<never, never>>,
    'master-users': RouteRecordInfo<'master-users', '/master/users', Record<never, never>, Record<never, never>>,
    'master-users-admin': RouteRecordInfo<'master-users-admin', '/master/users/admin', Record<never, never>, Record<never, never>>,
    'master-users-admin-add-edit-admin-dialog': RouteRecordInfo<'master-users-admin-add-edit-admin-dialog', '/master/users/admin/AddEditAdminDialog', Record<never, never>, Record<never, never>>,
    'master-users-driver': RouteRecordInfo<'master-users-driver', '/master/users/driver', Record<never, never>, Record<never, never>>,
    'master-users-driver-add-edit-driver-dialog': RouteRecordInfo<'master-users-driver-add-edit-driver-dialog', '/master/users/driver/AddEditDriverDialog', Record<never, never>, Record<never, never>>,
    'master-vehicle-vehicle-data': RouteRecordInfo<'master-vehicle-vehicle-data', '/master/vehicle/vehicle-data', Record<never, never>, Record<never, never>>,
    'master-vehicle-vehicle-data-add-edit-vehicle-data-dialog': RouteRecordInfo<'master-vehicle-vehicle-data-add-edit-vehicle-data-dialog', '/master/vehicle/vehicle-data/AddEditVehicleDataDialog', Record<never, never>, Record<never, never>>,
    'master-vehicle-vehicle-type': RouteRecordInfo<'master-vehicle-vehicle-type', '/master/vehicle/vehicle-type', Record<never, never>, Record<never, never>>,
    'master-vehicle-vehicle-type-add-edit-vehicle-type-dialog': RouteRecordInfo<'master-vehicle-vehicle-type-add-edit-vehicle-type-dialog', '/master/vehicle/vehicle-type/AddEditVehicleTypeDialog', Record<never, never>, Record<never, never>>,
    'report': RouteRecordInfo<'report', '/report', Record<never, never>, Record<never, never>>,
    'routing-order': RouteRecordInfo<'routing-order', '/routing/order', Record<never, never>, Record<never, never>>,
    'routing-order-add-edit-order-dialog': RouteRecordInfo<'routing-order-add-edit-order-dialog', '/routing/order/AddEditOrderDialog', Record<never, never>, Record<never, never>>,
    'routing-task': RouteRecordInfo<'routing-task', '/routing/task', Record<never, never>, Record<never, never>>,
    'routing-task-route-plan': RouteRecordInfo<'routing-task-route-plan', '/routing/task/route-plan', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
  }
}
